services:
  mariadb:
    image: mariadb:latest
    container_name: x-mariadb
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      TZ: ${TZ}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    healthcheck:
      test:
        - "CMD-SHELL"
        - 'mariadb-admin ping -h 127.0.0.1 -p"$${MYSQL_ROOT_PASSWORD}"'
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 40s
    volumes:
      - mariadb-data:/var/lib/mysql
      - ./drizzle:/docker-entrypoint-initdb.d:ro
    networks:
      - sre-network

  mariadb-exporter:
    image: prom/mysqld-exporter:latest
    container_name: x-mariadb-exporter
    restart: unless-stopped
    depends_on:
      - mariadb
    environment:
      DATA_SOURCE_NAME: "root:${MYSQL_ROOT_PASSWORD}@tcp(mariadb:3306)/"
    ports:
      - "9104:9104"
    volumes:
      - ./x-docker/mariadb-exporter/my.cnf:/etc/.my.cnf:ro
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:9104/metrics || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - sre-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: x-nextjs-app
    restart: unless-stopped
    networks:
      - sre-network
    depends_on:
      - mariadb
    environment:
      NODE_ENV: production
      PORT: 3000
      DATABASE_URL: "mysql://${MYSQL_USER}:${MYSQL_PASSWORD}@mariadb:3306/${MYSQL_DATABASE}"
    ports:
      - "80:3000"
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:3000/ || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3

networks:
  sre-network:
    external: true

volumes:
  mariadb-data:
